## NumPy Arrays


In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### Identity Matrics


In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.random.rand(5)


array([0.5563724 , 0.85512443, 0.8701957 , 0.27653938, 0.7318884 ])

In [14]:
np.random.randn(2)

array([ 0.37349175, -0.59414037])

In [15]:
np.random.randint(100)

79

In [21]:
arr =  np.random.randint(1,100,25)

In [23]:
arr.reshape(5,5)

array([[86, 62, 67, 93, 95],
       [79, 40, 78, 57, 44],
       [ 5, 60, 90, 58,  1],
       [92, 42, 28, 71, 44],
       [90, 36, 90, 22, 29]])

In [24]:
arr.max()

95

In [25]:
arr.min()

1

In [26]:
arr

array([86, 62, 67, 93, 95, 79, 40, 78, 57, 44,  5, 60, 90, 58,  1, 92, 42,
       28, 71, 44, 90, 36, 90, 22, 29])

In [27]:
arr

array([86, 62, 67, 93, 95, 79, 40, 78, 57, 44,  5, 60, 90, 58,  1, 92, 42,
       28, 71, 44, 90, 36, 90, 22, 29])

In [28]:
arr.argmax()

4

In [29]:
arr.argmin()

14

In [31]:
arr.shape

(25,)

In [32]:
arr.reshape(5,5)

array([[86, 62, 67, 93, 95],
       [79, 40, 78, 57, 44],
       [ 5, 60, 90, 58,  1],
       [92, 42, 28, 71, 44],
       [90, 36, 90, 22, 29]])

In [33]:
arr.shape

(25,)